grpc:
  server:
    port: 6567
server:
  port: 8989
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8088
  application:
    name: provider